"""source

Revision ID: 42bbead4f34a
Revises: cc1442a388af
Create Date: 2019-12-29 23:57:53.751117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42bbead4f34a'
down_revision = 'cc1442a388af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Article', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Article', 'source')
    # ### end Alembic commands ###
