"""empty message

Revision ID: 9e5fe6b38a6e
Revises: ad8abc274480
Create Date: 2020-01-25 19:50:48.259418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5fe6b38a6e'
down_revision = 'ad8abc274480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
