"""string to uuid

Revision ID: e93a1b81ea38
Revises: f9b2daf3c594
Create Date: 2020-01-25 19:31:21.857785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93a1b81ea38'
down_revision = 'f9b2daf3c594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
