"""user key

Revision ID: f9b2daf3c594
Revises: 32d72ccd2d7c
Create Date: 2020-01-25 19:14:09.309773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b2daf3c594'
down_revision = '32d72ccd2d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('key', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'key')
    # ### end Alembic commands ###
